FROM docker.io/library/ubuntu:22.04

# Config apt repositories
RUN apt update && apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
RUN add-apt-repository "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /"
RUN apt update

ENV DEBIAN_FRONTEND=noninteractive
RUN apt install -y git gcc make wget librdmacm-dev rdma-core libibverbs-dev libncurses5-dev libmount-dev libevent-dev libssl-dev libhiredis-dev liburing-dev pkg-config

# Install Python
ARG PYTHON_VERSION=3.12
RUN apt install -y python${PYTHON_VERSION} python${PYTHON_VERSION}-dev python${PYTHON_VERSION}-venv python3-pip
RUN python${PYTHON_VERSION} -m ensurepip --upgrade
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 10
RUN update-alternatives --install /usr/bin/python python /usr/bin/python${PYTHON_VERSION} 10
RUN update-alternatives --config python3
RUN python3 -m pip install --upgrade setuptools wheel pip pybind11

# Install cuda 12.1
RUN apt install -y cuda-12-1

# install cmake
RUN cd /tmp && \
    wget -q https://cmake.org/files/v4.1/cmake-4.1.3-linux-x86_64.sh && \
    bash cmake-4.1.3-linux-x86_64.sh --skip-license --prefix=/usr && \
    rm cmake-4.1.3-linux-x86_64.sh

# libevhtp uses TestEndianess.c.in
RUN ln -s /usr/share/cmake-4.1/Modules/TestEndianness.c.in /usr/share/cmake-4.1/Modules/TestEndianess.c.in

# install ucx
RUN cd /tmp && \
    wget -q https://github.com/openucx/ucx/releases/download/v1.19.0/ucx-1.19.0-ubuntu22.04-mofed5-cuda12-x86_64.tar.bz2 && \
    tar xvf ucx-1.19.0-ubuntu22.04-mofed5-cuda12-x86_64.tar.bz2 && \
    dpkg -i ucx-1.19.0.deb ucx-cuda-1.19.0.deb ucx-xpmem-1.19.0.deb && \
    rm /tmp/ucx-1.19.0-ubuntu22.04-mofed5-cuda12-x86_64.tar.bz2 /tmp/ucx-1.19.0.deb /tmp/ucx-cuda-1.19.0.deb /tmp/ucx-xpmem-1.19.0.deb

ADD . /root/priskv

WORKDIR /root/priskv
ENV CMAKE_POLICY_VERSION_MINIMUM=3.5

RUN mkdir /workspace
RUN make all PRISKV_USE_CUDA=1
RUN cp server/priskv-server /workspace/
RUN cp client/priskv-benchmark /workspace/
RUN cp client/priskv-client /workspace/
RUN cp cluster/client/priskv-cluster-benchmark /workspace/
RUN rm -rf /root/priskv

WORKDIR /workspace
ENTRYPOINT ["/workspace/priskv-server"]
